### ISSUE TITLE
Capsense Issue in BGM111

### ISSUE THREAD

**Issue by Ronnie4324** [balena-io/balena-fin-coprocessor-firmata#30]
Hi Everyone,

I am new in bgm111.
I am working on Capsense in BGM111
can anyone help me with some reference or sample code for it.

**Comment by Bucknalla** [comment]
Hi @Ronnie4324, this doesn't seem relevant to this repository, as this specifically targets the firmata firmware of BGM111 running on the balenaFin. I would suggest checking out https://www.silabs.com/community for sample code and/or reference projects.
